/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/lotting/': RouteRecordInfo<'/lotting/', '/lotting', Record<never, never>, Record<never, never>>,
    '/lotting/purchaseOrder/[id]': RouteRecordInfo<'/lotting/purchaseOrder/[id]', '/lotting/purchaseOrder/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/qrcode/': RouteRecordInfo<'/qrcode/', '/qrcode', Record<never, never>, Record<never, never>>,
    '/receivement/': RouteRecordInfo<'/receivement/', '/receivement', Record<never, never>, Record<never, never>>,
    '/receivement/purchaseOrder/[id]': RouteRecordInfo<'/receivement/purchaseOrder/[id]', '/receivement/purchaseOrder/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
